### ISSUE TITLE
Benchmark vs nikic/FastRoute

### ISSUE THREAD

**Issue by spartan** [alexdodonov/mezon-router#1]
Hi,

Just came across your library and it looks awesome.
Can you add https://github.com/nikic/FastRoute to the list of benchmarks ?

Thank you.

**Comment by alexdodonov** [comment]
Hi! If you want it - you'll get it )

**Comment by alexdodonov** [comment]
Hi! 

This banchmark can be found here - https://github.com/alexdodonov/mezon-router/blob/master/doc/fast-route.md

Can I close this issue?

**Comment by alexdodonov** [comment]
Looks like everything is OK
