### ISSUE TITLE
I cannot use dots in my routes, I've tried with types [s:param] and [fp:param] in the routes

### ISSUE THREAD

**Issue by lolix-kernel** [alexdodonov/mezon-router#16]
I am building a simple calculator with the router, like this:
```PHP
$router = new \Mezon\Router\Router();

$router->addRoute('add/[fp:firstNumber]/[fp:secondNumber]', 
    function (string $route, array $numbers) {
        $firstNumber = $numbers['firstNumber'];
        $secondNumber = $numbers['secondNumber'];

        echo $firstNumber + $secondNumber;
    }
);

$router->callRoute('/add/3.4/2.4');
// The requested resource /add/3.4/2.4 was not found on this server.
```

My calculator only works if I use this code:
```PHP
$router = new \Mezon\Router\Router();

$router->addRoute('index.php/add/[fp:firstNumber]/[fp:secondNumber]', 
    function (string $route, array $numbers) {
        $firstNumber = $numbers['firstNumber'];
        $secondNumber = $numbers['secondNumber'];

        echo $firstNumber + $secondNumber;
    }
);

$router->callRoute('index.php/add/3.4/2.4');
// Output: 5.8
```
And if I use ``` [s:parameters] ``` for example to display the number like a string I also have to add index.php in the route.

I don't know if there is another way to do this better.

**Comment by alexdodonov** [comment]
I have checked both your cases:
```php
$router->callRoute('/add/3.4/2.4');
$router->callRoute('index.php/add/3.4/2.4');
```
And all of them are working if I call `$router->callRoute(...);`

But there is no error message `The requested resource /add/3.4/2.4 was not found on this server.` in router.

I think that this message is shown by your HTTP server.

Show please the code wich passes REQUEST_URI to router.

Please check [this issue](https://github.com/alexdodonov/mezon-router/issues/9) may be it will help you. The solution is show in [this comment](https://github.com/alexdodonov/mezon-router/issues/9#issuecomment-745348247).

**Comment by jamessampford** [comment]
Is it because ‘addRoute’ doesn’t start with a forward slash in the first sample but ‘callRoute’ does?

**Comment by lolix-kernel** [comment]
Oh, sorry. My code works when I call the route with the method:
```PHP
$router->callRoute('add/3.4/2.4');
// Output 5.8
```
But the problem comes when I call the route from the browser with the same method, I have the error again:
```
Browser: localhost:8080/add/3.4/2.4
// The requested resource /add/3.4/2.4 was not found on this server.
```
It only works in the browser when I use this method:
```PHP
$router->callRoute($_GET['r']);
```
```
Browser: localhost:8080/?r=add/3.4/2.4
// Output: 5.8
```
To run my code I use this command: ``` php -S localhost:8080 ``` I don't know if maybe it is the problem or if the correct form is with ``` $router->callRoute($_GET['r']); ```

And thanks for getting back to me.

**Comment by lolix-kernel** [comment]
Yeah, like @alexdodonov said my error is my HTTP server and it isn't problem of the router, and in my case I am using the built-in php server but that is only for purpose only of development. 

And my code only works in the browser if I use this file and command:
```
File:
https://github.com/skilld-labs/docker-php/blob/master/.ht.router.php

Command:
php -S localhost:8080 .ht.router.php
```

So I think it's better to use a real HTTP server like apache or nginx. 
By the way what is the HTTP server that are you using?

And thank you so much again.

**Comment by lolix-kernel** [comment]
And I have a proposal could I write more documentation about the router?, such as which are all methods of the router and an example of their use.

Example: a simple app with the router
```PHP
$router = new \Mezon\Router\Router();  // It creates a new object of the class Router

// We add a new dynamic route with the parameter 'name'
$router->addRoute('/hello/[a:name]',
    function (string $route, array $parameters) {
        $name = $parameters['name'];
        echo "hello $name";
    }
);

// And we call the route
$router->callRoute('hello/world');

// Output: hello world
```

But if this is unnecessary I understand

**Comment by alexdodonov** [comment]
@lolix-kernel 

> So I think it's better to use a real HTTP server like apache or nginx.

Sure you need some HTTP server's mechanism wich process unexisting URL `/add/3.4/2.4` and call add.php instead of it. In Apache you should use .htaccess, nginx I think have something like it.

> By the way what is the HTTP server that are you using?

Apache, but Mezon Router can work with nginx too.

> And I have a proposal could I write more documentation about the router?

Sure. Create a fork, update documentation and make pull request. I will be glad if you will help with the documentation.

And thank you too )

**Comment by lolix-kernel** [comment]
> @lolix-kernel
> 
> > So I think it's better to use a real HTTP server like apache or nginx.
> 
> Sure you need some HTTP server's mechanism wich process unexisting URL `/add/3.4/2.4` and call add.php instead of it. In Apache you should use .htaccess, nginx I think have something like it.
> 
> > By the way what is the HTTP server that are you using?
> 
> Apache, but Mezon Router can work with nginx too.
> 
> > And I have a proposal could I write more documentation about the router?
> 
> Sure. Create a fork, update documentation and make pull request. I will be glad if you will help with the documentation.
> 
> And thank you too )

Ok, thank you so much @alexdodonov.

**Comment by alexdodonov** [comment]
@lolix-kernel you are welcome ) Feel free to submit other questions and feature requests.
