### ISSUE TITLE
Making benchmark suite public

### ISSUE THREAD

**Issue by hbgl** [alexdodonov/mezon-router#17]
Hello.
In the README, the only stated reason for using mezon-router is speed. But there is no straight forward way to verify your benchmark results. I think that making the benchmark suite publicly available would add a lot of credibility to the numbers.

**Comment by alexdodonov** [comment]
Hello, done - https://github.com/alexdodonov/mezon-router-benchmark

Hope it will be usefull.

Is it OK now? )

**Comment by hbgl** [comment]
Hi. Thanks for getting back on the issue. I opened a new issue in the benchmark repository about some improvement suggestions: https://github.com/alexdodonov/mezon-router-benchmark/issues/1
