### ISSUE TITLE
How dose it work?

### ISSUE THREAD

**Issue by JwanKaro** [alexdodonov/mezon-router#18]
Hi there.
I've been trying to create a route and dispatch it, but I couldn't. For example in klein router you can make it like this:
```
// to add a route 
  $router->respond($path, function ($request, $response) {

    });
// and then dispatch it 
$rotuer->dispatch();
```

it will be very helpful if you create an example.

thanks for your work.
best regards

**Comment by JwanKaro** [comment]
As far I understand your you. I have to call each route back? 
Like if I generate pages dynamic  I have to create for each page a file?

**Comment by alexdodonov** [comment]
Hi!

Here is a small example:

```php
// $app is your app class or controller or something like that

$router = new \Mezon\Router\Router();
$router->addRoute( '/first-route/' , [ $app , 'foo' ] );
$router->addRoute( '/second/route/' , [ $app , 'bar' ] );
$router->addRoute( '/the/third/route/' , [ $app , 'helloWorld' ] );

$router->callRoute($_SERVER['REQUEST_URI']);

// or call it like this $router->callRoute($_GET['r']);
```

And thats all.

Unlike Klein you generate response and dispatch it in one call of the, for example, `[ $app , 'foo' ]`.

Was it helpfull?

**Comment by JwanKaro** [comment]
Yes bro 😁.
Thanks for your help and here is your star ⭐

**Comment by danielsteiner** [comment]
I hate to dig up old, closed issues but calling the route via $router->callRoute($_SERVER['REQUEST_URI']); sends the whole path including parameters to the parameter. 

```
function test($id) {
 var_dump($id);
}

$router->addRoute('/test/[i:id]', [$testController, 'test'], 'GET');
$router->callRoute($_SERVER['REQUEST_URI']);
```

outputs 
```
test/1234
```

when going to to /test/1234. how to omit the route from the var?

**Comment by alexdodonov** [comment]
@danielsteiner Hi!

Try please

```php
function test($route, $params) {
 var_dump($params);
}
```

**Comment by danielsteiner** [comment]
Thanks, got it. I thought i can move over my controllers from laravel without changing the function signature. Works well now.

**Comment by alexdodonov** [comment]
You are welcome )
