### ISSUE TITLE
Model binding

### ISSUE THREAD

**Issue by obayesshelton** [alexdodonov/mezon-router#2]
If I were to implement this in Laravel does it support model binding?

**Comment by alexdodonov** [comment]
Not yet. You mean Laravel's models binding? Or any third-party models implementations?

**Comment by fernandorotermund** [comment]
Compared to Slim?

**Comment by alexdodonov** [comment]
@fernandorotermund yes I have compariison with Slim: https://github.com/alexdodonov/mezon-router/blob/master/doc/router-slim.md

**Comment by obayesshelton** [comment]
Laravel model binding - [](https://laravel.com/docs/7.x/routing)

**Comment by alexdodonov** [comment]
@obayesshelton thanks)

**Comment by alexdodonov** [comment]
@obayesshelton done - https://github.com/alexdodonov/mezon-router#middleware-and-model-binding
Can I close this issue?
