### ISSUE TITLE
Optionnal route parameters ?

### ISSUE THREAD

**Issue by maxonss** [alexdodonov/mezon-router#20]
Hey there,

I would like the second parameter `uuid` to be optional, is there a way to handle this differently ?
```
$router->addRoute('/events/[a:action]/', function ($route, $parameters) { /* some code */});

$router->addRoute('/events/[a:action]/[a:uuid]', function ($route, $parameters) { /* some code */});
```

I hope my question is not that bad won't hurt your eyes 🥶 

Huge thanks for your work, it helped me a lot, you can count on me for sharing to the world your project !

**Comment by alexdodonov** [comment]
Hi! Change initialization order:
```php
$router->addRoute('/events/[a:action]/[a:uuid]', ...);
//and only then
$router->addRoute('/events/[a:action]/', ...);
```

**Comment by maxonss** [comment]
Hey Alex,

Thank you for your quick answer, yes it helped :D
