### ISSUE TITLE
How are routes and regex cached and compiled inside mezon router.??

### ISSUE THREAD

**Issue by kingx619** [alexdodonov/mezon-router#21]
I can see that the methods dumpOnDisk(); and loadFromDisk inside the routeSet trait are not linked and used anywhere inside the code. I just want to understand how mezon router caching is done for regex and the routes...?? I can also see warmRoutes(); method not being used anywhere in the main Router code. .Can you explain it Alex

**Comment by alexdodonov** [comment]
Hi! You are right - you should look at the method `warmRoutes`. You will find caching details in it. 

But using this method or not should be descided by the client code. Mezon Router just provides such functionality.

The main idea - is to provide ability to start using Mezon Router with minimum amount of lines of code. And then step by step improve performance with caching and dumping on disk.

**Comment by kingx619** [comment]
I cannot see the warmRoutes();  method being used anywhere insie the code. You have provided it as the option. But I cannot see it being used any where to cache the contents. Please let me know how this router is caching the contents and precompiling the regexps inside caches

**Comment by alexdodonov** [comment]
Here is the example https://github.com/alexdodonov/mezon-router-benchmark/blob/main/Benchmarks/Mezon/MezonReactParamBench.php

**Comment by kingx619** [comment]
Thanks for the info

**Comment by alexdodonov** [comment]
Can I close the issue now?

**Comment by alexdodonov** [comment]
Hi! Check this please:

```php
// prepare cache
$router = new Router();

// add routes
$router->addRoute(/* route and controller */);
$router->addRoute(/* route and controller */);
$router->addRoute(/* route and controller */);
...

// dumping routes on disk
$router->dumpOnDisk('cache.static.php');

// reading routes from cache
$router->loadFromDisk('cache.static.php');
``` 

Hope it will be usefull )

**Comment by lee-php** [comment]
Thanks for your quick reply.

About the cache, each time the code is executed, the cache will be written and read through dumpOnDisk() and loadFromDisk() methods.

How can the cache improve performance?  
I don't understand how it works.  :-)

**Comment by alexdodonov** [comment]
You need to split this code:

```php
// somewhere in your CI/CD pipeline - warming cache
$router = new Router();

// add routes
$router->addRoute(/* route and controller */);
$router->addRoute(/* route and controller */);
$router->addRoute(/* route and controller */);
...

// dumping routes on disk
$router->dumpOnDisk('cache.static.php');
```

```php
// somewhere in your application code - using this cache
$router->loadFromDisk('cache.static.php');
```

**Comment by lee-php** [comment]
I tested the caching function  in my local environment, and an error was returned:

```
// create router
$router = new  \Mezon\Router\Router();

// additing routes
$router->addRoute('/article/[i:id]', [new \App\Admin\Controllers\ArticleController(), 'mod'], 'GET');

// dumping routes on disk
$router->dumpOnDisk(\Core\App::Config()->get('route_path'));

// reading routes from cache
$router->loadFromDisk(\Core\App::Config()->get('route_path'));

// calling route
$router->callRoute($_SERVER['REQUEST_URI']);
```
return Fatal error:
```
Fatal error: Uncaught Error: Call to undefined method App\Admin\Controllers\ArticleController::__set_state() in E:\web\lee-php\runtime\route.php:37 Stack trace: #0 E:\web\lee-php\vendor\mezon\router\Mezon\Router\RoutesSet.php(204): require() #1 E:\web\lee-php\public\mezon.php(24): Mezon\Router\Router->loadFromDisk() #2 {main} thrown in E:\web\lee-php\runtime\route.php on line 37
```
cache php:
```
...
1 => 
  array (
    'GET' => 
    array (
      0 => 
      array (
        'bunch' => 
        array (
          2 => 
          array (
            'pattern' => 'article/[i:id]',
            'callback' => 
            array (
              0 => 
              App\Admin\Controllers\ArticleController::__set_state(array(
              )),
              1 => 'mod',
            ),
          ),
        ),
        'regexp' => '~^(?|article/([-+]{0,1}[0-9]+))$~',
      ),
    ),
    'POST' => 
    array (
    ),
    'PUT' => 
    array (
    ),
    'DELETE' => 
    array (
    ),
    'OPTION' => 
    array (
    ),
    'PATCH' => 
    array (
    ),
  ),
...
```
