### ISSUE TITLE
Do you have a todo list for the router?

### ISSUE THREAD

**Issue by lolix-notepad** [alexdodonov/mezon-router#26]
I want to help in the code, but I don't know what to add to the router.

And by the way, can a wiki be a good idea?

**Comment by alexdodonov** [comment]
>>> Why the router cannot cache the routes?

It can, but we need two versions of router. One version wich works in react style. In this case caching will be extremly usefull. And the second case when router is called once per script execution. In this case cache can slow down the application. But I'am not sure. It must be benchmarked.

>>> I'll do it, and I was thinking, can a CLI for the framework mezon be a good idea? (like to create controllers, a basic structure folder, and so on).

Look for this repo: https://github.com/alexdodonov/mezon-cli there are two tasks. Do you want to do them?

>>> I was talking about a wiki on github, but I was also thinking to make a documentation website for the framework mezon, made with itself.

Still in progress.

**Comment by lolix-notepad** [comment]
> It can, but we need two versions of router. One version wich works in react style. In this case caching will be extremly usefull. And the second case when router is called once per script execution. In this case cache can slow down the application. But I'am not sure. It must be benchmarked.

Ok. I understand it now, thank you.

> Look for this repo: https://github.com/alexdodonov/mezon-cli there are two tasks. Do you want to do them?

Yes, I do. I'll try to make it pretty well. (The two tasks are: create default folder structure and create application class, aren't they?)

> Still in progress.

I'll wait for it.

---

PS: keep it up with your good job.

**Comment by alexdodonov** [comment]
> Yes, I do. I'll try to make it pretty well. (The two tasks are: create default folder structure and create application class, aren't they?)

Yes, two tasks.
