### ISSUE TITLE
Update benchmark using the Symfony router

### ISSUE THREAD

**Issue by nicolas-grekas** [alexdodonov/mezon-router#3]
As I posted in my comment on [this blog post](https://dev.to/alexdodonov/new-php-router-wich-is-7-to-15-times-faster-then-symfony-router-2o5c), the benchmark used in this work is using the slowest path supported by the Symfony Router.

If you really want to compare its performance to your work, you should use the CompiledUrlMatcher.

AFAIK, this is the fastest PHP Router existing to date.
I would be very (and happily) surprised if your router were (significantly) faster. Let me know!

Check https://medium.com/@nicolas.grekas/making-symfonys-router-77-7x-faster-1-2-958e3754f0e1 for some background on the technology.

**Comment by alexdodonov** [comment]
Thanks for your detailed comment - I shall create a new benchmark soon

**Comment by alexdodonov** [comment]
Hi! I have benchmarked CompiledUrlMatcher - https://dev.to/alexdodonov/real-life-comparison-of-symfony-router-and-mezon-router-1hb5

**Comment by nicolas-grekas** [comment]
Thanks, I've already commented on it :)

You've got the wiring right, but `$dumper->getCompiledRoutes()` should never be called in a loop.

The way this is supposed to be used is:

1. warm the list of routes by dumping the compiled routes once (eg using var_export() to generate a cache.php 
2. reuse the already dumped routes in the loop.

**Comment by spartan** [comment]
@nicolas-grekas Is there a throughly written documentation for these types of optimizations? 
Not sure how many developers would know how to use these optimizations.
Having a very complex system in general could reduce speed.

**Comment by alexdodonov** [comment]
@spartan list of described optimizations can be found in his articles:

https://medium.com/@nicolas.grekas/making-symfonys-router-77-7x-faster-1-2-958e3754f0e1
https://medium.com/@nicolas.grekas/making-symfony-router-lightning-fast-2-2-19281dcd245b

**Comment by alexdodonov** [comment]
@nicolas-grekas I have improved the benchmark according to your feedback - https://dev.to/alexdodonov/real-life-comparison-of-symfony-router-and-mezon-router-26m0
Now it is working much faster

**Comment by nicolas-grekas** [comment]
@alexdodonov great thanks :)

**Comment by alexdodonov** [comment]
@nicolas-grekas thanks for yor feedback. Hope i can close this issue
