### ISSUE TITLE
Non-ASCII character support

### ISSUE THREAD

**Issue by Robinjoeh** [alexdodonov/mezon-router#33]
Hi.

Have you been considering adding `urldecode()` or similar to support non-ascii characters such as `εεεεεε`?

**Currently, the router returns an error for this:**
```
The processor was not found for the route %CE%B5%CE%B5%CE%B5%CE%B5%CE%B5%CE%B5/test
```

I added `urldecode()` to the `Utils::prepareRoute` static method as a temporary solution.

**Comment by alexdodonov** [comment]
@Robinjoeh 

Hi!
Thanks for this issue - i shall implement it.

**Comment by alexdodonov** [comment]
Hi! Sorry for the long reply. Try please version 1.4.0 - hope it will help you.

Is it OK now?

**Comment by Robinjoeh** [comment]
Hi!

Based on the commits it seems it is the same code change I did, so yes this is a working solution.
Well done, thanks!

Closing this.
