### ISSUE TITLE
[Q] How can I use it correctly?

### ISSUE THREAD

**Issue by B0bbyD0llar** [alexdodonov/mezon-router#36]
Hello,
I would like to achieve the following goal (see code) and unfortunately I can't get it to run. Do you have a tip?

```php
        $router = new Router();
        $router->addRoute('/user/edit/[i:id]', ['APP\User\UserEditController', 'edit'], 'GET', 'UserEdit');
        $router->callRoute($_SERVER['REQUEST_URI']); // URI = http://localhost/user/edit/5353
````
So the router should now create an instance of "APP\User\UserEditController" and call the method "edit" with the parameter "id".

Can I realize this scenario with mezon-router?

**Comment by alexdodonov** [comment]
@B0bbyD0llar Hi!

Yes you can. Please look at this issue: https://github.com/alexdodonov/mezon-router/issues/34

Use middleware for your purposes.

**Comment by B0bbyD0llar** [comment]
Hi,
Sorry, but I don't get it with this example. I don't want an instance at all as "callable", instead I just want the class. 
Also, I don't want to pass a request object to the target function at all, just the parameters with the correct typecast as defined in the route.

I may not be advanced enough to use this type of router and I should just stick with my working router.
