### ISSUE TITLE
How to get access to the raw request body?

### ISSUE THREAD

**Issue by ricardoalcocer** [alexdodonov/mezon-router#37]
With Klein routes, you get the $request and $response arguments as part of the callback for a route.

With Mezon, you get string $route, array $parameters, where route is the actual URL and parameters are any additional variables.

How do I get access to the raw request body?  Like if they are sending in any JSON or JWT?

Thanks.  Really looking forward to refactoring my API to use Mezon!

**Comment by alexdodonov** [comment]
@ricardoalcocer Hi!

You should use third party framewroks for working with requests/responses.

And then use middleware like in this issue - https://github.com/alexdodonov/mezon-router/issues/34

**Comment by ricardoalcocer** [comment]
Thanks. I'll have a look and will report back. 👍🏻
