### ISSUE TITLE
Comparison updates

### ISSUE THREAD

**Issue by jamessampford** [alexdodonov/mezon-router#8]
It would be nice to have updated comparisons between this and all of the frameworks being compared to in order to see any improvements made in terms of performance - may be able to automate this in a build process with Actions?

~~Could it also be possible to introduce versioning at some point too?~~

**Comment by alexdodonov** [comment]
@jamessampford 

>>> Could it also be possible to introduce versioning at some point too?

Could you please explain what versioning you are writing about?

**Comment by jamessampford** [comment]
@alexdodonov it seems I made a mistake about that, sorry!

Still would be great to have updated comparisons 👍

**Comment by alexdodonov** [comment]
@jamessampford comparisons were updated (see README.md). Can I close the issue now?

**Comment by jamessampford** [comment]
@alexdodonov looks good to me 👍 hope can periodically update the comparison and can improve performance greater still 😄
